name: food_express
description: A simple offline Food Delivery prototype with GetX and Hive.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
